### ISSUE TITLE
粒子效果是怎么做出来的？

### ISSUE THREAD

**Issue by chaoshuai** [sickworm/MISportsConnectWidget#3]
不断地去draw point吗？      还是point执行rotate？

**Comment by sickworm** [comment]
StarArgument对象会维护一个粒子的位置，x轴/y轴速度，透明度等信息，由独立线程根据公式不断计算新的信息值。onDraw时根据当前Point的对象的值画出来粒子，多少个粒子就有多少个StarArgument对象
